version: 3
updated_by: "codex"
notes: "OpenAlex-only ingestion. Populate openalex_source_id for each venue."
venues:
  - id: ieee_twc
    name: "IEEE Transactions on Wireless Communications"
    type: "journal"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_commmag
    name: "IEEE Communications Magazine"
    type: "journal"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_cst
    name: "IEEE Communications Surveys & Tutorials"
    type: "journal"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_jsac
    name: "IEEE Journal on Selected Areas in Communications"
    type: "journal"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_jsasp
    name: "IEEE Journal of Selected Topics in Signal Processing"
    type: "journal"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_tsp
    name: "IEEE Transactions on Signal Processing"
    type: "journal"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_tvt
    name: "IEEE Transactions on Vehicular Technology"
    type: "journal"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_tcom
    name: "IEEE Transactions on Communications"
    type: "journal"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_icc
    name: "IEEE International Conference on Communications"
    type: "conference"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_globecom
    name: "IEEE Global Communications Conference"
    type: "conference"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_wcnc
    name: "IEEE Wireless Communications and Networking Conference"
    type: "conference"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_wcl
    name: "IEEE Wireless Communications Letters"
    type: "journal"
    publisher: "IEEE"
    openalex_source_id: null
  - id: ieee_vtc
    name: "IEEE Vehicular Technology Conference"
    type: "conference"
    publisher: "IEEE"
    openalex_source_id: null
